changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Misc
      labels:
