name: Lint & Test

on:
  push:
    branches: develop
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Label PR
        if: github.event_name == 'pull_request'
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.3
        with:
          commit_message: "[REBASE] Run formatter/linter"
      - name: Test all
        run: |
          sbt test
